version: '2.3'
services:
  mysql:
    image: mysql:5.7.20
    container_name: wso2ei-mysql
    ports:
      - 3306
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
      # mounting MySQL init scripts
      - ./mysql/scripts:/docker-entrypoint-initdb.d
      # mounting custom configurations
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  wso2ei-analytics-worker:
    image: wso2/wso2ei-analytics-worker:6.5.0
    container_name: wso2ei-analytics-worker
    ports:
      - 9091:9091
      - 9444:9444
    healthcheck:
      test: ["CMD", "nc", "-z","localhost", "9444"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 70s
    volumes:
      # mounting configurations
      - ./worker:/home/wso2carbon/wso2-config-volume
    depends_on:
      mysql:
        condition: service_healthy
  wso2ei-analytics-dashboard:
    image: wso2/wso2ei-analytics-dashboard:6.5.0
    container_name: wso2ei-analytics-dashboard
    ports:
      - 9643:9643
    healthcheck:
      test: ["CMD", "nc", "-z","localhost", "9643"]
      interval: 10s
      timeout: 120s
      retries: 5
      start_period: 70s
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./dashboard:/home/wso2carbon/wso2-config-volume
  wso2ei-broker:
    image: wso2/wso2ei-broker:6.5.0
    container_name: wso2ei-broker
    ports:
      - 9446:9446
      - 5675:5675
      - 8675:8675
      - 1886:1886
      - 8836:8836
      - 7614:7614
    healthcheck:
      test: ["CMD", "nc", "-z","localhost", "9446"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 90s
    volumes:
      # mounting configurations
      - ./broker:/home/wso2carbon/wso2-config-volume
    depends_on:
      mysql:
        condition: service_healthy
      wso2ei-analytics-worker:
        condition: service_healthy
      wso2ei-analytics-dashboard:
        condition: service_healthy
  wso2ei-integrator:
    image: wso2/wso2ei-integrator:6.5.0
    container_name: wso2ei-integrator
    ports:
      - 9443:9443
      - 8243:8243
      - 8280:8280
    healthcheck:
      test: ["CMD", "nc", "-z","localhost", "9443"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 90s
    volumes:
      # mounting configurations
      - ./integrator:/home/wso2carbon/wso2-config-volume
    depends_on:
      mysql:
        condition: service_healthy
      wso2ei-analytics-worker:
        condition: service_healthy
      wso2ei-analytics-dashboard:
        condition: service_healthy
      wso2ei-broker:
        condition: service_healthy
